# Generated by Django 2.2.12 on 2022-12-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otree_single_asset_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='available_cash',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='settled_cash',
            field=models.IntegerField(),
        ),
    ]
