# Generated by Django 2.2.12 on 2023-01-03 11:25

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('otree_single_asset_market', '0003_auto_20221229_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='clue_info',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='question_info',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
