# Generated by Django 2.2.12 on 2023-01-08 04:41

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('otree_single_asset_market', '0004_auto_20230103_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='available_cash',
            field=otree.db.models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='settled_cash',
            field=otree.db.models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
