# Generated by Django 2.2.12 on 2023-01-08 04:46

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('otree_single_asset_market', '0005_auto_20230108_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='available_cash',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='settled_cash',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
