# Generated by Django 2.2.12 on 2023-01-10 10:54

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('otree_single_asset_market', '0008_remove_player_first_round_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='first_round_counter',
            field=otree.db.models.IntegerField(default=1, null=True),
        ),
    ]
