# Generated by Django 2.2.12 on 2023-01-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otree_single_asset_market', '0009_player_first_round_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='first_round_counter',
        ),
    ]
